export const ADD_BUN = "ADD_BUN";
export const REMOVE_BUN = "REMOVE_BUN";
export const ADD_INGREDIANT = "ADD_INGREDIANT";
export const REMOVE_INGREDIANT = "REMOVE_INGREDIANT";
export const CHANGE_ORDER_INGREDIANTS = "CHANGE_ORDER_INGREDIANTS";
